version: '3'
services:
  kanban-postgres:
    image: "postgres:13.1"
    container_name: postgres-local
    ports:
      - 9999:5432
    environment:
      - POSTGRES_DB=github-crm
      - POSTGRES_PASSWORD=w23121991m
  nodejs-server:
    build:
      context: ./backend
    ports:
      - "3200:3200"
    container_name: node-api
  react-ui:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true