version: '3'
services:
  kanban-postgres:
    image: "postgres:13.1"
    container_name: postgres-local
    ports:
      - 9999:5432
    environment:
      - POSTGRES_DB=github-crm
      - POSTGRES_PASSWORD=w23121991m
    networks:
      - default
  nodejs-server:
    depends_on:
      - kanban-postgres
    build:
      context: ./backend
    ports:
      - "3200:3200"
    container_name: node-api
    networks:
      - default
  react-ui:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    networks:
      - default
networks:
  default:
    driver: bridge 
