version: '3'
services:
  postgres:
    image: "postgres:13.1"
    container_name: postgres-local
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=github-crm
      - POSTGRES_PASSWORD=w23121991m
    networks:
      - default
  nodejs-server:
    depends_on:
      - postgres
    build:
      context: ./backend
    ports:
      - "3200:3200"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASS=w23121991m
      - POSTGRES_DBNAME=github-crm
      - POSTGRES_PORT=5432
    container_name: node-api
    networks:
      - default
  react-ui:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    networks:
      - default
networks:
  default:
    driver: bridge 
